#!/bin/bash
#SBATCH --job-name=annotate
#SBATCH --output=annotate.log
#SBATCH --cpus-per-task=24
#SBATCH --partition=macmanes,shared

source activate orp_v2

cp assemblies/Hyla_cinerea_ORP.2.2.8.ORP.fasta .

diamond blastx -p 24 -e 1e-8 --top 0.1 -q Hyla_cinerea_ORP.2.2.8.ORP.fasta -d /mnt/lustre/macmaneslab/ams1236/Oyster_River_Protocol/software/diamond/swissprot -o cinerea.all.annotation.hits.txt

sort cinerea.all.annotation.hits.txt -k 1,1 -k11,11g | sort -u -k 1,1 --merge > cinerea.annotation.txt
sed "s/|/\t/g" cinerea.annotation.txt > tmp.fa
mv tmp.fa cinerea.annotation.txt
